foreground #c0caf5
background #1a1625

color0  #15111d
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #cba6f7
color5  #f5a9e1
color6  #89dceb
color7  #e9d5ff

color8  #4a3b56
color9  #f6a0bb
color10 #b7f0b1
color11 #fde7a8
color12 #d6b3ff
color13 #ffb7eb
color14 #a6e9f5
color15 #fff0fa

cursor #ffb7eb
selection_background #3a2947
selection_foreground #fff0fa
